site_name: ClarkePark
site_description: Transformaci칩n de Clarke y Park
copyright: Creado por Marco Polo J치come Toss
repo_url: https://clarkepark.readthedocs.io/

nav:
    - Instalaci칩n: index.md
    - Ejemplo pr치ctico : clarkepark.md
    - Referencias: references.md
    - Version : version.md

  

theme: readthedocs



markdown_extensions:
    - smarty
    
version: 0.1.4
    
plugins:
    - search:
        min_search_length: 2
        separator: '[\s\-\.]+'
